#!/bin/bash
source /etc/profile
#$ -S /bin/bash
#$ -pe pvm 1

#Load required modules - load manually via command line anyway
#modules GATK, miniconda and picard loaded from what is already on Argos
#module used are as follows, comment out when necessary

module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/miniconda3-4.6.14-gcc-5.4.0-kkzv7zk
module load /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/picard-2.19.0-gcc-5.4.0-hluyi36

python /home/ma1111/scripts/parallel_ASEreadcounter_XIST.py
